
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const SET_CATEGORY_NAME = "SET_CATEGORY_NAME"
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL"
export const ADD_TO_CART = "ADD_TO_CART"
export const ALL_PRODUCTS = "ALL_PRODUCTS"